# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'browserSignIn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

	# Pods for browserSignIn
	pod 'OktaOidc', '~> 3.0'

end
